server.port=8080

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.dqntlvzturzufhqzcdwe
spring.datasource.password=zihXi5dWUNu6B8l6

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
